In [4]:
#####  Phase1 : Model Creation #####
#####  Data Loading  ######
#Imports the pandas library for handling datasets /database / tables
import pandas as pd
ProductSet = pd.read_csv("Product_Finder_sample.csv")
ProductSet

    Multiplier  Product
0            1        4
1            2        8
2            3       12
3            4       16
4            5       20
5            6       24
6            7       28
7            8       32
8            9       36
9           10       40
10          11       44
11          12       48
12          13       52
13          14       56
14          15       60
15          16       64
16          17       68
17          18       72
18          19       76
19          20       80

In [6]:
Inp = ProductSet [["Multiplier"]]
Inp

    Multiplier
0            1
1            2
2            3
3            4
4            5
5            6
6            7
7            8
8            9
9           10
10          11
11          12
12          13
13          14
14          15
15          16
16          17
17          18
18          19
19          20

In [8]:
Out = ProductSet[["Product"]]
Out

    Product
0         4
1         8
2        12
3        16
4        20
5        24
6        28
7        32
8        36
9        40
10       44
11       48
12       52
13       56
14       60
15       64
16       68
17       72
18       76
19       80

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train, Y_test = train_test_split(Inp, Out,test_size = 0.30, random_state = 0)

In [11]:
X_train

    Multiplier
6            7
13          14
4            5
2            3
5            6
14          15
9           10
7            8
16          17
11          12
3            4
0            1
15          16
12          13

In [12]:
X_test

    Multiplier
18          19
1            2
19          20
8            9
10          11
17          18

In [13]:
Y_train

    Product
6        28
13       56
4        20
2        12
5        24
14       60
9        40
7        32
16       68
11       48
3        16
0         4
15       64
12       52

In [14]:
Y_test

    Product
18       76
1         8
19       80
8        36
10       44
17       72

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [17]:
weight = regressor.coef_
weight

array([[4.]])

In [18]:
bias = regressor.intercept_
bias

array([7.10542736e-15])

In [21]:
Y_predi = regressor.predict(X_test)
Y_predi

array([[76.],
       [ 8.],
       [80.],
       [36.],
       [44.],
       [72.]])

In [23]:
from sklearn.metrics import r2_score
R_Score = r2_score(Y_test,Y_predi)
R_Score

1.0

In [25]:
import pickle as pc
Filename = "SLR_Model_ProductFinder_Predict.sav"
Filename

'SLR_Model_ProductFinder_Predict.sav'

In [26]:
pc.dump(regressor, open(Filename,'wb'))

In [33]:
Loaded_Model = pc.load(open(Filename,'rb'))
Result1 = Loaded_Model.predict([[25]])
Result1

E:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[100.]])