In [44]:
#####  Phase1 : Model Creation : 50_StandUps Profit Predict  #####
#####  Data Loading  ######
#Imports the pandas library for handling datasets /database / tables
import pandas as pd

In [45]:
#Reads the CSV file into a pandas DataFrame Variable "Dataset"  
Dataset = pd.read_csv("50_Startups.csv")
#to display the dataset (rows and columns).
Dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [46]:
#Converts categorical columns into dummy/indicator variables (numerical form).
#Ensures the dummy values are stored as integers (0 and 1) instead of True/False.
#Drops the first category in each categorical column to avoid the dummy variable trap (multicollinearity).
Dataset = pd.get_dummies(Dataset, dtype = int, drop_first = True)
Dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [47]:
#Returns the list of all column names present in the DataFrame Dataset.
Dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='str')

In [48]:
#####  Feature Selection  ######
#Set the independent variables ('R&D Spend', 'Administration', 'Marketing Spend', 'State_Florida', 'State_New York')
Independent = Dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'State_Florida', 'State_New York']]
#To display the Independent -Input Values
Independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [49]:
#Set the dependent variable (Profit)
Dependent = Dataset[['Profit']]
#To display the Dependent -Output Values
Dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [50]:
######  Train-Test Split ######
#Imports the function to split data sklearn library and function model_selection.
from sklearn.model_selection import train_test_split
#Splits data into training and testing sets (30% test, 70% train) and Assigns training and testing sets to variables.
X_Train, X_Test, Y_Train, Y_Test = train_test_split(Independent, Dependent, test_size = 0.30, random_state = 0)

In [51]:
#Training data for independent variables.
X_Train

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
7   130298.13       145530.06        323876.68              1               0
14  119943.24       156547.42        256512.92              1               0
45    1000.23       124153.04          1903.93              0               1
48     542.05        51743.15             0.00              0               1
29   65605.48       153032.06        107138.38              0               1
15  114523.61       122616.84        261776.23              0               1
30   61994.48       115641.28         91131.24              1               0
32   63408.86       129219.61         46085.25              0               0
16   78013.11       121597.55        264346.06              0               0
42   23640.93        96189.63        148001.11              0               0
20   76253.86       113867.30        298664.47              0               0
43   15505.73       127382.30         35534.17              0               1
8   120542.52       148718.95        311613.29              0               1
13   91992.39       135495.07        252664.93              0               0
25   64664.71       139553.16        137962.62              0               0
5   131876.90        99814.71        362861.36              0               1
17   94657.16       145077.58        282574.31              0               1
40   28754.33       118546.05        172795.67              0               0
49       0.00       116983.80         45173.06              0               0
1   162597.70       151377.59        443898.53              0               0
12   93863.75       127320.38        249839.44              1               0
37   44069.95        51283.14        197029.42              0               0
24   77044.01        99281.34        140574.81              0               1
6   134615.46       147198.87        127716.82              0               0
23   67532.53       105751.03        304768.73              1               0
36   28663.76       127056.21        201126.82              1               0
21   78389.47       153773.43        299737.29              0               1
19   86419.70       153514.11             0.00              0               1
9   123334.88       108679.17        304981.62              0               0
39   38558.51        82982.09        174999.30              0               0
46    1315.46       115816.21        297114.46              1               0
3   144372.41       118671.85        383199.62              0               1
0   165349.20       136897.80        471784.10              0               1
47       0.00       135426.92             0.00              0               0
44   22177.74       154806.14         28334.72              0               0

In [52]:
#Testing data for independent variables.
X_Test

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
28   66051.52       182645.56        118148.20              1               0
11  100671.96        91790.61        249744.55              0               0
10  101913.08       110594.11        229160.95              1               0
41   27892.92        84710.77        164470.71              1               0
2   153441.51       101145.55        407934.54              1               0
27   72107.60       127864.55        353183.81              0               1
38   20229.59        65947.93        185265.10              0               1
31   61136.38       152701.92         88218.23              0               1
22   73994.56       122782.75        303319.26              1               0
4   142107.34        91391.77        366168.42              1               0
33   55493.95       103057.49        214634.81              1               0
35   46014.02        85047.44        205517.64              0               1
26   75328.87       144135.98        134050.07              1               0
34   46426.07       157693.92        210797.67              0               0
18   91749.16       114175.79        294919.57              1               0

In [53]:
#Training data for dependent variable.
Y_Train

       Profit
7   155752.60
14  132602.65
45   64926.08
48   35673.41
29  101004.64
15  129917.04
30   99937.59
32   97427.84
16  126992.93
42   71498.49
20  118474.03
43   69758.98
8   152211.77
13  134307.35
25  107404.34
5   156991.12
17  125370.37
40   78239.91
49   14681.40
1   191792.06
12  141585.52
37   89949.14
24  108552.04
6   156122.51
23  108733.99
36   90708.19
21  111313.02
19  122776.86
9   149759.96
39   81005.76
46   49490.75
3   182901.99
0   192261.83
47   42559.73
44   65200.33

In [54]:
#Testing data for dependent variable.
Y_Test

       Profit
28  103282.38
11  144259.40
10  146121.95
41   77798.83
2   191050.39
27  105008.31
38   81229.06
31   97483.56
22  110352.25
4   166187.94
33   96778.92
35   96479.51
26  105733.54
34   96712.80
18  124266.90

In [55]:
#####  Model Training  #####
#Imports Linear Regression model
from sklearn.linear_model import LinearRegression
#Creates a regression model object.
regressor = LinearRegression()
#Trains the model using training data(Input and output data).
regressor.fit(X_Train, Y_Train)

LinearRegression()

In [56]:
#####  Model Parameters  #####
#Retrieves the slope(w) (coefficient) of the regression line.
weight = regressor.coef_
weight

array([[7.90840255e-01, 3.01968165e-02, 3.10148566e-02, 4.63028992e+02,
        3.04799573e+02]])

In [57]:
#Retrieves the intercept(b) of the regression line.
bias = regressor.intercept_
bias

array([42403.87087053])

In [58]:
#####  Prediction  #####
#Predicts salaries for test data.
Y_Predict = regressor.predict(X_Test)
#To display predicted salary values.
Y_Predict

array([[104282.76472172],
       [132536.88499212],
       [133910.85007766],
       [ 72584.77489417],
       [179920.9276189 ],
       [114549.31079234],
       [ 66444.43261346],
       [ 98404.96840122],
       [114499.82808602],
       [169367.50639895],
       [ 96522.6253998 ],
       [ 88040.6718287 ],
       [110949.99405525],
       [ 90419.1897851 ],
       [128020.46250064]])

In [59]:
#####  Model Evaluation  #####
#Imports R² score function
from sklearn.metrics import r2_score
#Calculates accuracy of the model (how well predictions fit actual data).
R_Score = r2_score(Y_Test, Y_Predict)
#To display the R² score.
R_Score

0.9358680970046243

In [60]:
#####  Model Saving & Loading  #####
#Imports pickle for saving/loading models.
import pickle as pc
#Defines filename for saving model.
FileName = "MLR_50StartUps_Phase1_Model.sav"
FileName

'MLR_50StartUps_Phase1_Model.sav'

In [61]:
#Saves trained model to file.
pc.dump(regressor,open(FileName,'wb'))

In [62]:
#Loads saved model back.
Loaded_Model = pc.load(open("MLR_50StartUps_Phase1_Model.sav",'rb'))
#Predicts profit using loaded model.
Result = Loaded_Model.predict([[22180.74, 154900.14,28400.72,1,0]])
#To display the predicted profit.
Result

E:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[65966.65730513]])